import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import abertura from '../public/abertura.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Reinauguração Fiorin Fiorello Modas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main + ' ' + 'mx-auto'}>
        <div className={styles.mainContainer + ' ' + 'mx-auto'}>
          <div className="columns-1 md:columns-2 text-center">
            <div className={styles.abertura}>
              <Image src={abertura} alt="Reinauguração Fiorin Fiorello Modas"/>
            </div>
            <div className={styles.abertura + ' ' + 'pr-8 pl-8 pt-8 pb-8'}>
              <h1 className="text-3xl font-bold mb-5">
                Convite de reinauguração
              </h1>
              <p className='mb-4'>Está chegando o grande dia!</p>
              <p className='mb-4'>A FIORIN FIORELLO convida você para a reinauguração  de nossa loja de acessórios e roupas femininas. </p>
              <p className='mb-4'>Será dia 11 de junho das 10h às 16h com um grande coquetel de boas vindas.</p>
              <p className='mb-4'>Venha fazer parte desse dia especial. Sua presença irá abrilhantar nosso dia! </p>
              <p className='mb-4'>Contamos com você!</p>
              <h3 className='mb-4 font-bold'>Confirme sua presença clicando no botão abaixo.</h3>
              <div className={styles.abertura + ' ' + 'pr-8 pl-8 pt-0 pb-8'}>
                <Link href="https://wa.me/5519974194636?text=Ol%C3%A1%21+Eu+%2Aestou+confirmando%2A+a+minha+presen%C3%A7a+na+%2AReinaugura%C3%A7%C3%A3o+da+Fiorin+Fiorello%2A+no+dia+%2A11+de+Jun+%C3%A0s+10%3A00%2A."> 
                  <a className='bg-neutral-900 text-white p-2 rounded font-bold text-3xl'>🙂 Eu vou</ a>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        Desenvolvido e criado por: <Link href="https://planoah.com/" className={styles.planoah}> Plano Ah!</Link>
      </footer>
    </div>
  )
}
